M48
; DRILL file {KiCad 9.0.1} date 2025-10-14T14:14:29+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-14T14:14:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.200
%
G90
G05
T1
X104.43Y-117.82
X110.21Y-117.82
T2
X121.0Y-114.0
T3
X116.0Y-119.0
X126.0Y-119.0
T4
X103.19Y-48.5
X110.81Y-48.5
T5
X89.5Y-46.5
X89.5Y-108.5
X124.5Y-46.5
X124.5Y-108.5
M30
